### PR TITLE
ci: Add blunderbluss.yml config

### PR DESCRIPTION
**Pull request by arriolac**
Add `blunderbluss.yml` config to auto assign issues and pull requests to the appropriate owner. Fill free to add other owners as well.

### CODE REVIEW

**Comment by jpoehnelt** [comment]
I added a CODEOWNERS which may make this moot.

**Comment by jpoehnelt** [comment]
https://github.com/googlemaps/fleet-debugger/blob/main/.github/CODEOWNERS

**Comment by arriolac** [comment]
@jpoehnelt still seeing blunderbuss auto-assigns. For example: https://github.com/googlemaps/fleet-debugger/pull/22

Does the .github blunderbuss.yml file need to be updated?

**Comment by jpoehnelt** [comment]
looks that way.

**Pull request closed without merging**
